<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 1/11/17
 * Time: 1:17 AM
 */

namespace app\components;


use app\models\LeadEsign;
use FPDI;
use Yii;

class PPINonAffiliate extends PdfEsign{
    public function export()
    {
        throw new \Exception("not yet implemented");
//        parent::export(); // TODO: Change the autogenerated stub
    }

} 