<?php

namespace app\models;

use Yii;
use yii\base\ModelEvent;
use yii\db\BaseActiveRecord;

/**
 * This is the model class for table "lead_esign".
 *
 * @property integer $id
 * @property string $salutation
 * @property string $firstname
 * @property string $middlename
 * @property string $lastname
 * @property string $account_provider
 * @property double $monthly_account_charge
 * @property string $client_signature_image
 * @property string $created_at
 * @property string $updated_at
 */
class LeadEsign extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lead_esign';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['salutation', 'firstname',  'lastname', 'monthly_account_charge', 'client_signature_image'], 'required'],
            [['monthly_account_charge'], 'number'],
            [['created_at','middlename', 'updated_at','account_provider'], 'safe'],
            [['salutation', 'firstname', 'middlename', 'lastname', 'account_provider', 'client_signature_image'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'salutation' => 'Salutation',
            'firstname' => 'Firstname',
            'middlename' => 'Middlename',
            'lastname' => 'Lastname',
            'account_provider' => 'Account Provider',
            'monthly_account_charge' => 'Monthly Account Charge',
            'client_signature_image' => 'Client Signature Image',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            $this->created_at = date("Y-m-d H:i:s");
        }else{
            $this->updated_at= date("Y-m-d H:i:s");
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
